adminPublic_index:
    path:     /
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:index" }
    methods:  GET

adminPublic_show:
    path:     /{id}/show
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:show" }
    methods:  GET

adminPublic_new:
    path:     /new
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:new" }
    methods:  [GET, POST]

adminPublic_create:
    path:     /create
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:create" }
    methods:  POST

adminPublic_edit:
    path:     /{id}/edit
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:edit" }
    methods:  [GET, POST]

adminPublic_update:
    path:     /{id}/update
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:update" }
    methods:  [POST, PUT]

adminPublic_delete:
    path:     /{id}/delete
    defaults: { _controller: "JeuArticleBundle:PublicAdmin:delete" }
    methods:  DELETE