adminProduits_index:
    path:     /{page}
    defaults:  
        _controller: "JeuArticleBundle:ArticlesAdmin:index"
        page:   1
    requirements: 
        page: \d*    
    methods:  GET

adminProduits_show:
    path:     /{id}/show
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:show" }
    methods:  GET

adminProduits_new:
    path:     /new
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:new" }
    methods:  [GET, POST]

adminProduits_create:
    path:     /create
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:create" }
    methods:  POST

adminProduits_edit:
    path:     /{id}/edit
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:edit" }
    methods:  [GET, POST]

adminProduits_update:
    path:  /{id}/update
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:update" }
    methods:  [POST,PUT]

adminProduits_delete:
    path:     /{id}/delete
    defaults: { _controller: "JeuArticleBundle:ArticlesAdmin:delete" }
    methods:  DELETE