adminAvis_index:
    path:     /{page}
    defaults:  
        _controller: "JeuArticleBundle:AvisAdmin:index" 
        page:   1
    requirements: 
        page: \d*    
    methods:  GET

adminAvis_show:
    path:     /{id}/show
    defaults: { _controller: "JeuArticleBundle:AvisAdmin:show" }
    methods:  GET

adminAvis_delete:
    path:     /{id}/delete
    defaults: { _controller: "JeuArticleBundle:AvisAdmin:delete" }
    methods:  DELETE