# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/avis/, role: ROLE_USER }
        
  encoders:
        Jeu\UserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       [ROLE_USER]
    ROLE_SUPER_ADMIN: [ROLE_ADMIN]

  providers:
    main:
      id: fos_user.user_provider.username      
      
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main_login:
        # Cette expression régulière permet de prendre /login (mais pas /login_check !)
        pattern:   ^/login$
        anonymous: true # On autorise alors les anonymes sur ce pare-feu    
      
    main:
      pattern:   ^/
      anonymous: true
      provider:  main # On change cette valeur      
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
        default_target_path: jeu_article_homepage
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     %secret%          