services:
#    jeu_article.example:
#        class: Jeu\ArticleBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirectionListener:
        class: Jeu\ArticleBundle\Listener\RedirectionListener
        arguments: ["@service_container","@session"]
        tags:
         - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    setNewReference:
        class: Jeu\ArticleBundle\Services\GetReference
        arguments: ['@security.authorization_checker','@doctrine.orm.entity_manager']

    setNewFacture:
        class: Jeu\ArticleBundle\Services\GetFacture
        arguments: ['@service_container']        