<?php

namespace Jeu\ArticleBundle\Repository;

/**
 * ExtensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtensionRepository extends \Doctrine\ORM\EntityRepository
{
}
