<?php

namespace Jeu\ArticleBundle\Repository;

/**
 * PublicJeuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PublicJeuRepository extends \Doctrine\ORM\EntityRepository
{
}
