<?php

namespace Jeu\UserBundle\Repository;

/**
 * PromoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromoRepository extends \Doctrine\ORM\EntityRepository
{
	public function findPromo($promo)
	{
		$query = $this->createQueryBuilder('a')
			->where('a.promo = :promo')
			->andWhere('a.utilise = 0')
			->setParameter('promo',$promo)
			;
		return $query->getQuery()->getResult();
	}
}
