<?php

namespace Jeu\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUtilisateurs($page, $nbPerPage)
	{
		$query = $this->createQueryBuilder('a')
		  ->getQuery()
		;

		$query
		  // On définit l'annonce à partir de laquelle commencer la liste
		  ->setFirstResult(($page-1) * $nbPerPage)
		  // Ainsi que le nombre d'annonce à afficher sur une page
		  ->setMaxResults($nbPerPage)
		;

		// Enfin, on retourne l'objet Paginator correspondant à la requête construite
		// (n'oubliez pas le use correspondant en début de fichier)
		return new Paginator($query, true);
	}
	
	public function getCommandes()
	{
		$qb = $this->createQueryBuilder('a');
		$qb
			->leftJoin('a.commandes','c')
			->addselect('count(c.id) as nbcommandes')
			->groupBy('a.username')
			->orderBy('nbcommandes','DESC')
			->setMaxResults(5)
			;
		return $qb->getQuery()->getResult();
	}
}
