<?php

namespace Jeu\UserBundle\Repository;

/**
 * UserAdressesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAdressesRepository extends \Doctrine\ORM\EntityRepository
{
}
