<?php

namespace Proxies\__CG__\Jeu\ArticleBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Caracteristiques extends \Jeu\ArticleBundle\Entity\Caracteristiques implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'id', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'tactique', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'rejouabilite', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'chance', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'diplomatie', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'reflexion', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'difficulte'];
        }

        return ['__isInitialized__', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'id', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'tactique', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'rejouabilite', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'chance', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'diplomatie', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'reflexion', '' . "\0" . 'Jeu\\ArticleBundle\\Entity\\Caracteristiques' . "\0" . 'difficulte'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Caracteristiques $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTactique($tactique)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTactique', [$tactique]);

        return parent::setTactique($tactique);
    }

    /**
     * {@inheritDoc}
     */
    public function getTactique()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTactique', []);

        return parent::getTactique();
    }

    /**
     * {@inheritDoc}
     */
    public function setRejouabilite($rejouabilite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRejouabilite', [$rejouabilite]);

        return parent::setRejouabilite($rejouabilite);
    }

    /**
     * {@inheritDoc}
     */
    public function getRejouabilite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRejouabilite', []);

        return parent::getRejouabilite();
    }

    /**
     * {@inheritDoc}
     */
    public function setChance($chance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChance', [$chance]);

        return parent::setChance($chance);
    }

    /**
     * {@inheritDoc}
     */
    public function getChance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChance', []);

        return parent::getChance();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiplomatie($diplomatie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiplomatie', [$diplomatie]);

        return parent::setDiplomatie($diplomatie);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiplomatie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiplomatie', []);

        return parent::getDiplomatie();
    }

    /**
     * {@inheritDoc}
     */
    public function setReflexion($reflexion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReflexion', [$reflexion]);

        return parent::setReflexion($reflexion);
    }

    /**
     * {@inheritDoc}
     */
    public function getReflexion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReflexion', []);

        return parent::getReflexion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDifficulte($difficulte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDifficulte', [$difficulte]);

        return parent::setDifficulte($difficulte);
    }

    /**
     * {@inheritDoc}
     */
    public function getDifficulte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDifficulte', []);

        return parent::getDifficulte();
    }

}
